sudo: false
language: python
cache: pip
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run --source=requests_oauthlib -m nose
after_success:
  - coveralls
